### ISSUE TITLE
Cant install on windows

### ISSUE THREAD

**Issue by pdeva** [foxyblocks/grunt-emblem#1]
I get this error when i do an npm install with grunt-emblem in my package.json

gyp http 200 http://nodejs.org/dist/v0.10.5/x64/node.lib
gyp http 200 http://nodejs.org/dist/v0.10.5/node.lib
gyp http 200 http://nodejs.org/dist/v0.10.5/x64/node.lib
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
c:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\include\xlocale(342): warning C4530: C++ exception handler used, but unwind semantics are not e
nabled. Specify /EHsc [F:\code\apmserver\apmgui\src\main\webapp\node_modules\grunt-emblem\node_modules\jsdom\node_modules\contextify\build\binding.sl
n]
C:\Users\P.node-gyp\0.10.5\deps\v8\include\v8.h(184): warning C4506: no definition for inline function 'v8::Persistent<T> v8::Persistent<T>::New(v8:
:Handle<T>)' [F:\code\apmserver\apmgui\src\main\webapp\node_modules\grunt-emblem\node_modules\jsdom\node_modules\contextify\build\binding.sln]
C:\Users\P.node-gyp\0.10.5\deps\v8\include\v8.h(184): warning C4506: no definition for inline function 'v8::Persistent<T> v8::Persistent<T>::New(v8:
:Handle<T>)' [F:\code\apmserver\apmgui\src\main\webapp\node_modules\grunt-emblem\node_modules\jsdom\node_modules\contextify\build\binding.sln]
LINK : fatal error LNK1181: cannot open input file 'C:\Users\P.node-gyp\0.10.5\node.lib' [F:\code\apmserver\apmgui\src\main\webapp\node_modules\gru
nt-emblem\node_modules\jsdom\node_modules\contextify\build\binding.sln]
Project : warning PRJ0018: The following environment variables were not found: [F:\code\apmserver\apmgui\src\main\webapp\node_modules\grunt-emblem\no
de_modules\jsdom\node_modules\contextify\build\binding.sln]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:784:12)
gyp ERR! System Windows_NT 6.2.9200
gyp ERR! command "node" "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd F:\code\apmserver\apmgui\src\main\webapp\node_modules\grunt-emblem\node_modules\jsdom\node_modules\contextify
gyp ERR! node -v v0.10.5
gyp ERR! node-gyp -v v0.9.5
gyp ERR! not ok
npm ERR! contextify@0.1.5 install: `node-gyp rebuild`
npm ERR! `cmd "/c" "node-gyp rebuild"` failed with 1
npm ERR!
npm ERR! Failed at the contextify@0.1.5 install script.
npm ERR! This is most likely a problem with the contextify package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls contextify
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install"
npm ERR! cwd F:\code\apmserver\apmgui\src\main\webapp
npm ERR! node -v v0.10.5
npm ERR! npm -v 1.2.18
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     F:\code\apmserver\apmgui\src\main\webapp\npm-debug.log
npm ERR! not ok code 0

**Comment by MajorBreakfast** [comment]
Any chance for a grunt-emblem based on PhantomJS?
